### PR TITLE
Do not restrict mirrors to taobao

### PR DESCRIPTION
**Pull request by szubster**
Otherwise I couldn't use https://cnpmjs.org or self-hosted mirrors.

### CODE REVIEW

**Comment by bonigarcia** [comment]
Please don't change the original format rules (indentation and so on).

**Comment by szubster** [comment]
Fixed, just being used to CRLF and this repo has mixed content.

**Comment by bonigarcia** [comment]
The new test included in this PR is failing:

```
    @Test
    public void testOtherMirrorUrl() throws  Exception {
        chromedriver().config().setAvoidAutoVersion(true)
                .setChromeDriverMirrorUrl(
                        new URL("https://cnpmjs.org/mirrors/chromedriver/"));
        chromedriver().useMirror().forceDownload().setup();

        File binary = new File(chromedriver().getBinaryPath());
        assertTrue(binary.exists());
    }
```

The traces are the following:

```
2019-08-29 11:38:26 [main] DEBUG i.g.bonigarcia.wdm.WebDriverManager.getLatestVersion(124) -- Latest version of chromedriver according to https://cnpmjs.org/mirrors/chromedriver/LATEST_RELEASE is 76.0.3809.126
Aug 29, 2019 11:38:27 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {s}->https://cnpmjs.org:443: The target server failed to respond
Aug 29, 2019 11:38:27 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://cnpmjs.org:443
Aug 29, 2019 11:38:31 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {s}->https://cnpmjs.org:443: The target server failed to respond
Aug 29, 2019 11:38:31 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://cnpmjs.org:443
Aug 29, 2019 11:38:32 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {s}->https://cnpmjs.org:443: The target server failed to respond
Aug 29, 2019 11:38:32 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://cnpmjs.org:443
Aug 29, 2019 11:38:39 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {s}->https://cnpmjs.org:443: The target server failed to respond
Aug 29, 2019 11:38:39 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://cnpmjs.org:443
Aug 29, 2019 11:38:42 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {s}->https://cnpmjs.org:443: The target server failed to respond
Aug 29, 2019 11:38:42 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://cnpmjs.org:443
Aug 29, 2019 11:38:44 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {s}->https://cnpmjs.org:443: The target server failed to respond
Aug 29, 2019 11:38:44 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://cnpmjs.org:443
Aug 29, 2019 11:38:46 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {s}->https://cnpmjs.org:443: The target server failed to respond
Aug 29, 2019 11:38:46 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://cnpmjs.org:443
2019-08-29 11:38:47 [main] WARN  i.g.bonigarcia.wdm.WebDriverManager.handleException(729) -- There was an error managing chromedriver 76.0.3809.126 (Remote host closed connection during handshake) ... trying again using cache and mirror
2019-08-29 11:38:48 [main] ERROR i.g.bonigarcia.wdm.WebDriverManager.handleException(733) -- There was an error managing chromedriver 76.0.3809.126 (Remote host closed connection during handshake)
javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1002)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at io.github.bonigarcia.wdm.HttpClient.execute(HttpClient.java:169)
	at io.github.bonigarcia.wdm.WebDriverManager.getDriversFromMirror(WebDriverManager.java:998)
	at io.github.bonigarcia.wdm.ChromeDriverManager.getDrivers(ChromeDriverManager.java:81)
	at io.github.bonigarcia.wdm.WebDriverManager.filterCandidateUrls(WebDriverManager.java:750)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:543)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:731)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:557)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:260)
	at io.github.bonigarcia.wdm.test.TaobaoTest.testOtherMirrorUrl(TaobaoTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at sun.security.ssl.InputRecord.read(InputRecord.java:505)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	... 47 common frames omitted
```

@szubster: Do you know the reason?

**Comment by szubster** [comment]
@bonigarcia They were working fine in build https://travis-ci.org/bonigarcia/webdrivermanager/builds/577936292 and locally.
I suppose some error on cnpmjs.org side? It's hard not to have flaky tests with dependencies on external services.

**Comment by bonigarcia** [comment]
Indeed it is a flaky test, likely due to cnpmjs.org. It randomly fails or passes (locally and also in Travis). I have ignored the test.

**Comment by szubster** [comment]
@bonigarcia Would you be so kind and make a release?

**Comment by bonigarcia** [comment]
This is implemented in version 3.7.0. But better use version 3.7.1, just released.

**Pull request merged**
