### PR TITLE
Fixing issue with binary existence validation

### PR DESCRIPTION
**Pull request by stas-slu**
Following an issue we had in our team, that used webdrivermanager to manage it's binaries- binary file (in this case, chromedriver) have been deleted. It's directories path exists as it was.  But, ```!targetFile.getParentFile().exists()``` lead to false approval as if the binary exists.

So, fixed this by making the binary existence validation to consider directories path as well. Until now, if the directories existed, although the driver itself were deleted, it will be considered as if the binary exists.

### CODE REVIEW

**Comment by bonigarcia** [comment]
I tested your PR but it is not working properly in all situations, but your approach is good.

Due to the fact that code has changed a bit, I am going to take in consideration your change for the next patch.

Thank you.

**Comment by stas-slu** [comment]
Sorry it took some time to answer. Can you please elaborate what kind of situations didn't worked? I would lake to take care with that and assist with the project :)

**Comment by bonigarcia** [comment]
Your patch introduced some changes in the location of the binaries in the local repositories. This shouldn't happen.

Of course you are welcome to assist the project. I tried to solve the issue you expose in the new version of WebDriverManager, released yesterday (1.4.0). If you are willing to contribute, please check out the latest version and test if now the problem is solved. If you still find that or another issue, please open another PR since this is closed.

Thank you.

**Comment by stas-slu** [comment]
Ok, I will see the latest changes :)
BTW, I didn't changed the location itself, but the validation of the driver location. Didn't gone that far :)

**Pull request closed without merging**
