### PR TITLE
Add namespace context for Saxon compatibility

### PR DESCRIPTION
**Pull request by andruhon**
A fix for https://github.com/bonigarcia/webdrivermanager/issues/486

### Purpose of changes
The WebdriverManager has recently stopped working with Saxon. This change adds namespace context to make it work with Saxon xPath factory.

### Types of changes
- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### How has this been tested?
I created a custom build for our test suite to make it work. It works in our teamcity.

### CODE REVIEW

**Comment by bonigarcia** [comment]
I never saw this problem happening. How can it be reproduced?

**Comment by andreikondratev** [comment]
In order to have this issue the Webdriver Manager has to be used in project with Saxon which by default respects xml namespaces. 
It was working fine, but I think the XML at https://chromedriver.storage.googleapis.com/ has recently changed and now has the S3 namespace `http://doc.s3.amazonaws.com/2006-03-01`.

**Comment by bonigarcia** [comment]
@andreikondratev I tried to reproduce this issue but I cannot. I created a new project using Selenium WebDriver and WebDriverManager, available here: https://github.com/bonigarcia/webdrivermanager-basic

Then, I added the Saxon dependency to the project, but the tests are still running nicely:

```
        <dependency>
            <groupId>net.sf.saxon</groupId>
            <artifactId>Saxon-HE</artifactId>
            <version>10.1</version>
            <scope>test</scope>
        </dependency>
```

Any clue about how to reproduce the issue with this setup?

**Comment by andruhon** [comment]
Hi! Can this be a difference of Saxon-HE and Saxon-PE? Let me try this project with Saxon-PE.

**Comment by xlemmingx** [comment]
Can confirm this issue occuring with this saxon dependency:
<dependency>
	<groupId>net.sf.saxon</groupId>
	<artifactId>Saxon-HE</artifactId>
	<version>9.5.1-8</version>
</dependency>

**Comment by bonigarcia** [comment]
@xlemmingx Yes, I tried to reproduce the error with that version of Saxon-HE, thank you.

Thanks a lot to everyone for contributing. I am merging this PR.

**Comment by andreikondratev** [comment]
Sorry I didn't help to test the quickstart. School holidays knocked me out.

**Pull request merged**
