### PR TITLE
Add marionette driver support

### PR DESCRIPTION
**Pull request by rosolko**
Add support for new firefox webdriver.
[Marionette](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette)

### CODE REVIEW

**Comment by bonigarcia** [comment]
Hi there,

Thanks a lot for the PR, looks very nice.

Let me test it. After that I'll be glad to merge it to the master branch and release a new version to Maven Central.

Kind regards,
Boni

**Comment by rosolko** [comment]
@bonigarcia 
Just keep in the mind, for testing you need Firefox version 45+ (for now it is Beta or Dev(Nightly)) but you can try on stable version.

Good luck

**Comment by bonigarcia** [comment]
@rosolko 

I executed the test you implemented (`MarionetteTest`) in Linux, and I found a problem. Since the package is a gz file, the decompression failed (since it is expecting a zip file). I suppose in Windows it works perfect, but not in Linux (nor Mac). Could you please review this issue please?

I think it could be easily solved (see similar code on method `unBZip2` in `Downloader` class). Thanks a lot!

**Comment by rosolko** [comment]
@bonigarcia Ok, I look at this issue later.

**Comment by rosolko** [comment]
@bonigarcia I'm facing little problem.
Marionette driver binary for linux delivery as `.gz` pack.
And seems like `rauschig jarchivelib` can't resolve `.gz` compression type w/o `tar` archive format.

**Comment by bonigarcia** [comment]
Indeed, unfortunately it seems that `jarchivelib` does not support just `.gz` files. Nevertheless you can implement this with something like the following:

```
    File archive = new File("/path/to/wires-0.6.2-linux64.gz");
    File target = new File(archive.getParentFile() + File.separator + "wires");
    GZIPInputStream gzin = new GZIPInputStream(new FileInputStream(archive));
    FileOutputStream fout = new FileOutputStream(target);
    for (int c = gzin.read(); c != -1; c = gzin.read()) {
      fout.write(c);
    }
    fout.close();
    gzin.close();
    target.setExecutable(true);
```

**Comment by rosolko** [comment]
@bonigarcia 
Sorry for delay. I've just implement method to extract `.gz` files.
Test it on linux and it's working well.

**Pull request merged**
