### PR TITLE
Edge driver url

### PR DESCRIPTION
**Pull request by rdmrtn**
### Purpose of changes
https://github.com/MicrosoftEdge/EdgeWebDriver/issues/146

### Types of changes

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### How has this been tested?
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Using WebDriverManager to resolve edge
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Using msedgedriver 125.0.2535.92 (resolved driver for Edge 125)
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Reading https://msedgewebdriverstorage.blob.core.windows.net/edgewebdriver/?restype=container&comp=list to seek msedgedriver
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Reading https://msedgewebdriverstorage.blob.core.windows.net/edgewebdriver/?restype=container&comp=list&marker=2%21104%21MDAwMDMzITEyNC4wLjI0NzcuMC9lZGdlZHJpdmVyX3dpbjY0LnppcCEwMDAwMjghOTk5OS0xMi0zMVQyMzo1OTo1OS45OTk5OTk5WiE- to seek msedgedriver
[main] INFO io.github.bonigarcia.wdm.online.Downloader - Downloading https://msedgewebdriverstorage.blob.core.windows.net/edgewebdriver/125.0.2535.92/edgedriver_linux64.zip
[main] INFO io.github.bonigarcia.wdm.online.Downloader - Extracting driver from compressed file edgedriver_linux64.zip
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Driver location: /home/eartan/Projects/visiumgo/webdrivermanager/msedgedriver

### CODE REVIEW

**Comment by rdmrtn** [comment]
Ok

**Comment by bonigarcia** [comment]
I believe this PR is no longer required. There was a bug related to msedgedriver (#1320) but it has been fixed in the master branch. Please double check the latest release of WebDriverManager, i.e. version 5.9.2.

**Comment by rdmrtn** [comment]
I do not understand why it is no longer required. 
When getDriversFromXml (https://github.com/bonigarcia/webdrivermanager/blob/01b185310aa8d0c541196b652cd8f300ca40c1d5/src/main/java/io/github/bonigarcia/wdm/WebDriverManager.java#L1567) is called, it will not get latest driver information because Azure Blob Storage requires marker parameter to fetch all pages.

https://github.com/bonigarcia/webdrivermanager/issues/1320 is similar but not same issue.

**Comment by bonigarcia** [comment]
That logic (reading from XML to discover edgedriver versions) should not be executed since the driver versions should be found using the online endpoints, e.g., https://msedgedriver.azureedge.net/LATEST_RELEASE_127_WINDOWS

So, I have just committed a patch to avoid that logic in the Edge Manager class: https://github.com/bonigarcia/webdrivermanager/commit/f6263e899e22bc6662065722e1a62e9a46570003

Also, you should not change the value of the property `wdm.edgeDriverUrl`. And your code does not even compile:

https://github.com/bonigarcia/webdrivermanager/actions/runs/10039350820/job/27920720228?pr=1323

```
Error:  COMPILATION ERROR : 
[1822](https://github.com/bonigarcia/webdrivermanager/actions/runs/10039350820/job/27920720228?pr=1323#step:5:1823)[INFO] -------------------------------------------------------------
[1823](https://github.com/bonigarcia/webdrivermanager/actions/runs/10039350820/job/27920720228?pr=1323#step:5:1824)Error:  /home/runner/work/webdrivermanager/webdrivermanager/src/main/java/io/github/bonigarcia/wdm/WebDriverManager.java:[1594,63] cannot find symbol
[1824](https://github.com/bonigarcia/webdrivermanager/actions/runs/10039350820/job/27920720228?pr=1323#step:5:1825) symbol:   class URIBuilder
[1825](https://github.com/bonigarcia/webdrivermanager/actions/runs/10039350820/job/27920720228?pr=1323#step:5:1826) location: class io.github.bonigarcia.wdm.WebDriverManager
```

Many thanks for your effort but I cannot merge this PR.

**Comment by bonigarcia** [comment]
After further investigation, I realized that reading the Edge driver versions from XML can still be helpful in some cases. So please resolve the compilation failures, and I will merge this PR.

**Comment by rdmrtn** [comment]
I've fixed the problem. Thanks.

**Pull request merged**
