### PR TITLE
Updated chrome download URL pattern

### PR DESCRIPTION
**Pull request by nick-etuk**
### Purpose of changes

Fixes this issue: Webdriver manager is not supporting latest chrome version
https://github.com/bonigarcia/webdrivermanager/issues/1221
### Types of changes

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### How has this been tested?

Tested by using the new URL pattern in test runs with Selenium (with Serenity BDD) locally and in CI pipelines.

### CODE REVIEW

**Comment by bertolini10** [comment]
Thanks @nick-etuk!

**Comment by IncredibleLou** [comment]
Thanks @nick-etuk  Hopefully, it will be merged soon :)

**Comment by bonigarcia** [comment]
Thanks for contributing, @nick-etuk!

**Comment by AbhishekSnapone** [comment]
I AM also getting the Same issue.

**Comment by AnushabalanTK** [comment]
> @bonigarcia Hi! Do you know when this fix is going to be available in mvnrepository?

Available now

**Pull request merged**
