### PR TITLE
Fix CustomTargetTest for Windows OS with long username

### PR DESCRIPTION
**Pull request by AlexanderPoleschuk**

### CODE REVIEW

**Comment by bonigarcia** [comment]
This PR seems not necessary anymore. There is a real change `.toRealPath()` in a test, which is basically nothing.

**Comment by AlexanderPoleschuk** [comment]
Not really...
We still need this change.

In CustomTargetTest.java in method testTargetPath() you have line
`assertThat(binaryPath, startsWith(tmpFolder.toString()));` that fails due to the long username is replaced with some short one that contains **~**. 

As far as temp folder is created, it stores value C:\Users\ALEXAN~1\AppData\Local\Temp\8265114436259440200 in tmpFolder variable.

Then in getTargetPath() method from Config.java it's replaced to some broken one:
**C:\Users\ALEXANC:**\Users\AlexanderPoleschuk1\AppData\Local\Temp\8265114436259440200
at line: 
```
if (path.contains(HOME)) {
    path = path.replace(HOME, System.getProperty("user.home"));
}
```
and the test fails on assertThat().

.toRealPath() returns a real unmodified path to the folder, like: C:\Users\AlexanderPoleschuk\AppData\Local\Temp\6542379686934004291
That's why the test passes on the assert message with .toRealPath().

Here is the failure I have w/o .toRealPath():
io.github.bonigarcia.wdm.WebDriverManagerException: java.lang.IllegalArgumentException: Parameter 'directory' is not a directory: C:\Users\ALEXANC:\Users\AlexanderPoleschuk1\AppData\Local\Temp\9029314181623417145

**Comment by AlexanderPoleschuk** [comment]
Long story short:
Without this change the test case will FAIL on WIN OS for users which username's length is more than 8 characters.

**Comment by bonigarcia** [comment]
Ok, but the changes in the imports are really not needed. Please leave only the `.toRealPath()` in the changes.

**Comment by AlexanderPoleschuk** [comment]
Done. Also fixed one small typo.
For imports - it wasn't me, but IDEA's _Optimize imports on the fly_ setting. ^_^

**Pull request merged**
