### PR TITLE
#206 - better handling of latest version download

### PR DESCRIPTION
**Pull request by AlexanderPoleschuk**
During merge of this PR it would be nice to add wdm.useLatestVersion parameter to documentation w/ description.

This change still don't handle latest versions of 
1) IE driver, because of open issue: https://github.com/SeleniumHQ/selenium/issues/4978
2) phantomJS - because it don't have any available possibility to check latest version

### CODE REVIEW

**Comment by AlexanderPoleschuk** [comment]
Even more on this:
If we add 
```
<dependency>
    <groupId>org.apache.httpcomponents</groupId>
    <artifactId>fluent-hc</artifactId>
    <version>4.5.5</version>
</dependency>
```
to pom.xml, then the code:
```
HttpGet request = new HttpGet(url);
request.addHeader("User-Agent", USER_AGENT);

HttpResponse response = wdmHttpClient.execute(request);
BufferedReader rd = new BufferedReader(
new InputStreamReader(response.getEntity().getContent()));
latestVersion = IOUtils.toString(rd);
```
will turn in one-liner: 
`latestVersion = Request.Get(url).execute().returnContent().toString();`

But it's one more dependency in pom...

**Comment by bonigarcia** [comment]
@AlexanderPoleschuk Thank you very much for your effort but I am not merging this PR, sorry.

I don't like to read the LATEST_RELEASE info to find out the latest release. I prefer the way it is done right now, i.e. relying in the real URL links and getting from them the latest release. This way is more generic, and it avoid to rely in the LATEST_RELEASE info, which might be outdated from time to time.

**Comment by AlexanderPoleschuk** [comment]
Ok, your point is valid. 
But have you ever met the case where LATEST_RELEASE info was not updated once newer version of webdriver was released? 
My understanding is that webdriver teams update them when they understand that current latest webdriver is ready to be used by wide audience...

Pulling hundreds of links to check/grab the only binary to the system is not an elegant solution. The more new versions of webdriver are released - the MORE urls you have to pull and parse.

But with LATEST_RELEASE tag it always will have constant and short number of urls that needs to be parsed.

**Comment by asolntsev** [comment]
@bonigarcia I don't understand why you don't want to use LATEST_RELEASE. Apparently it's generated automatically and is always up-to-date. In this it'such more reliable than own algorithm that can be easily broken.

**Pull request closed without merging**
